# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

genhypergeo_vec <- function(U, L, z, prec = NULL, check_mode = TRUE, log = FALSE, backend = "mpfr") {
    .Call(`_hypergeo2_genhypergeo_vec`, U, L, z, prec, check_mode, log, backend)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_hypergeo2_RcppExport_registerCCallable`)
})
